name: operator-e2e-tests

on: 
  pull_request:
  push:
    branches:
    - master

jobs:
  tests:
    name: End-2-End tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v2
      with:
          go-version: "^1.21.7"
    - name: Make dependencies
      run: make deps
    - name: Code generation
      run: make codegen
    - name: Run end-2-end tests
      run: make e2e
